name: "ESLint"
# description: "Lints JavaScript/TypeScript code."
# branding:
#   icon: check-circle
#   color: yellow

on:
  pull_request:
    branches: [develop]
    types: ["opened", "reopened", "ready_for_review", "synchronize"]

jobs:
  eslint:
    name: Lints TypeScript code
    runs-on: ubuntu-latest
    steps:
      - name: Change directory
        run: cd client
      - name: Install all dependencies for project
        run: yarn install
      - name: eslint
        run: npm run lint
